config/routes.rb
Simpleapp::Application.routes.draw do
  resources :contactus

end

app/models/contactu.rb
class Contactu < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contactus_controller.rb
class ContactusController < ApplicationController
  # GET /contactus
  # GET /contactus.xml
  def index
    @contactus = Contactu.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @contactus }
    end
  end

  # GET /contactus/1
  # GET /contactus/1.xml
  def show
    @contactu = Contactu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @contactu }
    end
  end

  # GET /contactus/new
  # GET /contactus/new.xml
  def new
    @contactu = Contactu.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @contactu }
    end
  end

  # GET /contactus/1/edit
  def edit
    @contactu = Contactu.find(params[:id])
  end

  # POST /contactus
  # POST /contactus.xml
  def create
    @contactu = Contactu.new(params[:contactu])

    respond_to do |format|
      if @contactu.save
        format.html { redirect_to(@contactu, :notice => 'Contactu was successfully created.') }
        format.xml  { render :xml => @contactu, :status => :created, :location => @contactu }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @contactu.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contactus/1
  # PUT /contactus/1.xml
  def update
    @contactu = Contactu.find(params[:id])

    respond_to do |format|
      if @contactu.update_attributes(params[:contactu])
        format.html { redirect_to(@contactu, :notice => 'Contactu was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @contactu.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contactus/1
  # DELETE /contactus/1.xml
  def destroy
    @contactu = Contactu.find(params[:id])
    @contactu.destroy

    respond_to do |format|
      format.html { redirect_to(contactus_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contactus_helper.rb
module ContactusHelper
end

app/views/contactus/_form.html.erb
<%= form_for(@contactu) do |f| %>
  <% if @contactu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contactu.errors.count, "error") %> prohibited this contactu from being saved:</h2>

      <ul>
      <% @contactu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contactus/edit.html.erb
<h1>Editing contactu</h1>

<%= render 'form' %>

<%= link_to 'Show', @contactu %> |
<%= link_to 'Back', contactus_path %>

app/views/contactus/index.html.erb
<h1>Listing contactus</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Subject</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contactus.each do |contactu| %>
  <tr>
    <td><%= contactu.name %></td>
    <td><%= contactu.email %></td>
    <td><%= contactu.subject %></td>
    <td><%= contactu.message %></td>
    <td><%= link_to 'Show', contactu %></td>
    <td><%= link_to 'Edit', edit_contactu_path(contactu) %></td>
    <td><%= link_to 'Destroy', contactu, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contactu', new_contactu_path %>

app/views/contactus/new.html.erb
<h1>New contactu</h1>

<%= render 'form' %>

<%= link_to 'Back', contactus_path %>

app/views/contactus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @contactu.name %>
</p>

<p>
  <b>Email:</b>
  <%= @contactu.email %>
</p>

<p>
  <b>Subject:</b>
  <%= @contactu.subject %>
</p>

<p>
  <b>Message:</b>
  <%= @contactu.message %>
</p>


<%= link_to 'Edit', edit_contactu_path(@contactu) %> |
<%= link_to 'Back', contactus_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simpleapp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>